drop-chance:
  COAL_ORE: 75
  IRON_ORE: 60
  GOLD_ORE: 50
  REDSTONE_ORE: 35
  LAPIS_ORE: 25
  EMERALD_ORE: 15
  DIAMOND_ORE: 10
  ANCIENT_DEBRIS: 5
rewards:
  COAL_ORE: 1
  IRON_ORE: 2
  GOLD_ORE: 4
  REDSTONE_ORE: 8
  LAPIS_ORE: 16
  EMERALD_ORE: 32
  DIAMOND_ORE: 64
  ANCIENT_DEBRIS: 128